### ISSUE TITLE
Jobs are failing with "No such kernel named conda-root-py"

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#267]
The following jobs are affected:
- container-testpilottest-pipeline
- addon-okr-data-to-s3
- txp-pulse-etl
- txp-snoozetabs-etl

```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/mnt1/ -Xmx15000M -Xms1000M
[NbConvertApp] Searching [u'/home/hadoop/analyses/output', '/home/hadoop/.jupyter', '/home/hadoop/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/hadoop/anaconda2/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/hadoop/.jupyter
[NbConvertApp] Looking for jupyter_config in /home/hadoop/analyses/output
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/hadoop/anaconda2/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/hadoop/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/hadoop/analyses/output
[NbConvertApp] Converting notebook ../container_pipeline.ipynb to notebook
[NbConvertApp] Notebook name is 'container_pipeline'
[NbConvertApp] Applying preprocessor: ExecutePreprocessor
[NbConvertApp] Executing notebook with kernel: conda-root-py
[NbConvertApp] Native kernel (python2) available from /home/hadoop/anaconda2/lib/python2.7/site-packages/ipykernel/resources
Traceback (most recent call last):
  File "/home/hadoop/anaconda2/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/notebook.py", line 26, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 141, in preprocess
    cwd=path)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 429, in start_new_kernel
    km.start_kernel(**kwargs)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 230, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-root-py
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/mnt1/ -Xmx15000M -Xms1000M
[NbConvertApp] WARNING | pattern u'container_pipeline.ipynb' matched no files
Command exiting with ret '1'
```

**Comment by vitillo** [comment]
cc @harterrt

**Comment by maurodoglio** [comment]
Yeah, jupyter notebook and nbconvert don't see the installed kernels in the same way. We need to force nbconvert to use python2:
```bash
jupyter nbconvert --ExecutePreprocessor.kernel_name=python2 ...
```

**Comment by maurodoglio** [comment]
This was fixed by https://github.com/mozilla/emr-bootstrap-spark/pull/71
