### ISSUE TITLE
txp-pulse-etl job is failing

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#269]
cc @sunahsuh 

```
    Py4JJavaErrorTraceback (most recent call last)

    <ipython-input-23-cf489c0bc09e> in <module>()
    ----> 1 local_final = sqlContext.createDataFrame(final.collect()).coalesce(1).write.mode("overwrite")    .parquet("s3n://telemetry-parquet/harter/cliqz_profile_daily/v1/")
    

    /usr/lib/spark/python/pyspark/rdd.py in collect(self)
        774         """
        775         with SCCallSiteSync(self.context) as css:
    --> 776             port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
        777         return list(_load_from_socket(port, self._jrdd_deserializer))
        778 


    /usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py in __call__(self, *args)
       1131         answer = self.gateway_client.send_command(command)
       1132         return_value = get_return_value(
    -> 1133             answer, self.gateway_client, self.target_id, self.name)
       1134 
       1135         for temp_arg in temp_args:


    /usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
         61     def deco(*a, **kw):
         62         try:
    ---> 63             return f(*a, **kw)
         64         except py4j.protocol.Py4JJavaError as e:
         65             s = e.java_exception.toString()


    /usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
        317                 raise Py4JJavaError(
        318                     "An error occurred while calling {0}{1}{2}.\n".
    --> 319                     format(target_id, ".", name), value)
        320             else:
        321                 raise Py4JError(


    Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
    : org.apache.spark.SparkException: Job 8 cancelled because SparkContext was shut down
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:818)
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:816)
    	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:816)
    	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1685)
    	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:83)
    	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1604)
    	at org.apache.spark.SparkContext$$anonfun$stop$8.apply$mcV$sp(SparkContext.scala:1781)
    	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1290)
    	at org.apache.spark.SparkContext.stop(SparkContext.scala:1780)
    	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend$MonitorThread.run(YarnClientSchedulerBackend.scala:108)
    	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
    	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
    	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:453)
    	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
    	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    	at py4j.Gateway.invoke(Gateway.java:280)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.GatewayConnection.run(GatewayConnection.java:214)
    	at java.lang.Thread.run(Thread.java:745)

```

**Comment by rafrombrc** [comment]
@vitillo @sunahsuh Do we know if this is still happening?

**Comment by sunahsuh** [comment]
I'm pretty sure this was a freak thing from aws shutting down the cluster
or something - we haven't seen this particular issue again

**Comment by rafrombrc** [comment]
Great, thanks! I'm closing this issue. We can reopen or open a new one if the problem resurfaces.
