### ISSUE TITLE
ImportError: No module named 'atmo.clusters.jobs'

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-analysis-service#408]
```
app@a898b116953a:~$ ./manage.py update_clusters
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/app/atmo/clusters/management/commands/update_clusters.py", line 6, in <module>
    from ...jobs import update_clusters
ImportError: No module named 'atmo.clusters.jobs'
```

**Comment by jezdez** [comment]
Nice, just goes to show that nobody ever used this management command ;D

This is a simple fix, the clusters app was previously using RQ whose pattern is to use `jobs.py` files for the async jobs (not related to *Spark* jobs). The management command just needs a correct import:

```python
from ...tasks import update_clusters
# ...
```
