### ISSUE TITLE
Failed job bhr-stacks

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#450]
The job has failed for the last few days, so it'd make sense to look into this. Pinging @mikeconley.

The run (j-3SPJYWEK8LXHK) failed with:

```python
accum = sc.accumulator(0)
def calculate_total_sessions_length(ping):
    accum.add(ping['payload/info/subsessionLength'])

windows_pings_only.foreach(calculate_total_sessions_length)
total_sessions_length_s = accum.value
total_sessions_length_m = total_sessions_length_s / 60

total_sessions_length_m

```

    

    Py4JJavaErrorTraceback (most recent call last)

    <ipython-input-9-0a90aa3474d5> in <module>()
          3     accum.add(ping['payload/info/subsessionLength'])
          4 
    ----> 5 windows_pings_only.foreach(calculate_total_sessions_length)
          6 total_sessions_length_s = accum.value
          7 total_sessions_length_m = total_sessions_length_s / 60

    /usr/lib/spark/python/pyspark/rdd.py in foreach(self, f)
        748                 f(x)
        749             return iter([])
    --> 750         self.mapPartitions(processPartition).count()  # Force evaluation
        751 
        752     def foreachPartition(self, f):

    /usr/lib/spark/python/pyspark/rdd.py in count(self)
       1006         3
       1007         """
    -> 1008         return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
       1009 
       1010     def stats(self):

    /usr/lib/spark/python/pyspark/rdd.py in sum(self)
        997         6.0
        998         """
    --> 999         return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
       1000 
       1001     def count(self):

    /usr/lib/spark/python/pyspark/rdd.py in fold(self, zeroValue, op)
        871         # zeroValue provided to each partition is unique from the one provided
        872         # to the final reduce call
    --> 873         vals = self.mapPartitions(func).collect()
        874         return reduce(op, vals, zeroValue)
        875 

    /usr/lib/spark/python/pyspark/rdd.py in collect(self)
        774         """
        775         with SCCallSiteSync(self.context) as css:
    --> 776             port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
        777         return list(_load_from_socket(port, self._jrdd_deserializer))
        778 

    /usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py in __call__(self, *args)
       1131         answer = self.gateway_client.send_command(command)
       1132         return_value = get_return_value(
    -> 1133             answer, self.gateway_client, self.target_id, self.name)
       1134 
       1135         for temp_arg in temp_args:

    /usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
         61     def deco(*a, **kw):
         62         try:
    ---> 63             return f(*a, **kw)
         64         except py4j.protocol.Py4JJavaError as e:
         65             s = e.java_exception.toString()

    /usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
        317                 raise Py4JJavaError(
        318                     "An error occurred while calling {0}{1}{2}.\n".
    --> 319                     format(target_id, ".", name), value)
        320             else:
        321                 raise Py4JError(

    Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
    : org.apache.spark.SparkException: Job aborted due to stage failure: Task 336 in stage 2.0 failed 4 times, most recent failure: Lost task 336.3 in stage 2.0 (TID 561, ip-172-31-0-58.us-west-2.compute.internal): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/worker.py", line 172, in main
        process()
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/worker.py", line 167, in process
        serializer.dump_stream(func(split_index, iterator), outfile)
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 317, in func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 748, in processPartition
      File "<ipython-input-9-0a90aa3474d5>", line 3, in calculate_total_sessions_length
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/accumulators.py", line 162, in add
        self._value = self.accum_param.addInPlace(self._value, term)
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/accumulators.py", line 212, in addInPlace
        value1 += value2
    TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
    
    	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
    	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
    	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
    	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
    	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
    	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
    	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
    	at org.apache.spark.scheduler.Task.run(Task.scala:86)
    	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    
    Driver stacktrace:
    	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
    	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
    	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
    	at scala.Option.foreach(Option.scala:257)
    	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
    	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
    	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
    	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
    	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
    	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
    	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
    	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:453)
    	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
    	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    	at py4j.Gateway.invoke(Gateway.java:280)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.GatewayConnection.run(GatewayConnection.java:214)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/worker.py", line 172, in main
        process()
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/worker.py", line 167, in process
        serializer.dump_stream(func(split_index, iterator), outfile)
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 2371, in pipeline_func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 317, in func
      File "/usr/lib/spark/python/pyspark/rdd.py", line 748, in processPartition
      File "<ipython-input-9-0a90aa3474d5>", line 3, in calculate_total_sessions_length
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/accumulators.py", line 162, in add
        self._value = self.accum_param.addInPlace(self._value, term)
      File "/mnt/yarn/usercache/hadoop/appcache/application_1494526327812_0001/container_1494526327812_0001_01_000004/pyspark.zip/pyspark/accumulators.py", line 212, in addInPlace
        value1 += value2
    TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
    
    	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
    	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
    	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
    	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
    	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
    	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
    	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
    	at org.apache.spark.scheduler.Task.run(Task.scala:86)
    	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	... 1 more

```python
def only_content_hangs(ping):
    result = []
    if ping['payload/childPayloads'] is None:
        return result
  
    for payload in ping['payload/childPayloads']:
        if 'threadHangStats' not in payload:
            return result
        for thread_hang in payload['threadHangStats']:
            if 'name' not in thread_hang:
                continue
            if thread_hang['name'] != 'Gecko_Child':
                continue
            if len(thread_hang['hangs']) > 0:
                result = result + thread_hang['hangs']
    return result
       
def only_parent_hangs(ping):
    result = []

    try:
        if not 'payload/threadHangStats' in ping:
            return result

        for thread_hang in ping['payload/threadHangStats']:
            if 'name' not in thread_hang:
                continue
            if thread_hang['name'] != 'Gecko':
                continue
            if len(thread_hang['hangs']) > 0:
                result = result + thread_hang['hangs']
    finally:
        return result
    
content_hangs = windows_pings_only.flatMap(only_content_hangs)
parent_hangs = windows_pings_only.flatMap(only_parent_hangs)
```

```python
# Scoring is total number of hangs > 100ms, divided by total
# sessionLength
def map_to_hang_sums(hang):
    hist_data = hang['histogram']['values']
    hist = pd.Series(hist_data.values(), index=map(int, hist_data.keys()))
    hang_sum = hist[hist.index >= 100].sum()
    return (tuple(hang['stack']), hang_sum)

grouped_content_hangs = content_hangs.map(map_to_hang_sums).reduceByKey(lambda a, b: a + b).collectAsMap()
grouped_parent_hangs = parent_hangs.map(map_to_hang_sums).reduceByKey(lambda a, b: a + b).collectAsMap()
```

```python
def group_by_top_frame(stacks):
    grand_total_hang_sum = 0
    top_frames = {}
    for stack, hang_sum in stacks.iteritems():
        if len(stack) == 0:
            continue
        stack_top_frame = stack[-1]
        if not stack_top_frame in top_frames:
            top_frames[stack_top_frame] = { "frame": stack_top_frame, "stacks": [], "hang_sum": 0 }

        top_frame = top_frames[stack_top_frame]

        # Keep stacks sorted by hits.
        top_frame["stacks"].append((stack, hang_sum))
        top_frame["stacks"].sort(key=lambda d: d[1], reverse=True)

        top_frame["hang_sum"] += hang_sum
        grand_total_hang_sum += hang_sum

    return top_frames, grand_total_hang_sum

content_top_frames, content_grand_total_hang_sum = group_by_top_frame(grouped_content_hangs)
parent_top_frames, parent_grand_total_hang_sum = group_by_top_frame(grouped_parent_hangs)
```

```python
def score(grouping):
    grouping['hang_sum'] = float(grouping['hang_sum']) / float(total_sessions_length_m) * 1000
    scored_stacks = []
    for stack_tuple in grouping['stacks']:
        score = float(stack_tuple[1]) / float(total_sessions_length_m) * 1000
        scored_stacks.append((stack_tuple[0], score))
        
    grouping['stacks'] = scored_stacks
    return grouping


scored_content_top_frames = {k: score(g) for k, g in content_top_frames.iteritems()}
scored_parent_top_frames = {k: score(g) for k, g in parent_top_frames.iteritems()}

sorted_content = sorted(scored_content_top_frames.values(), key=lambda d: d["hang_sum"], reverse=True)
sorted_parent = sorted(scored_parent_top_frames.values(), key=lambda d: d["hang_sum"], reverse=True)

```

    

    NameErrorTraceback (most recent call last)

    <ipython-input-13-20da15850b63> in <module>()
         10 
         11 
    ---> 12 scored_content_top_frames = {k: score(g) for k, g in content_top_frames.iteritems()}
         13 scored_parent_top_frames = {k: score(g) for k, g in parent_top_frames.iteritems()}
         14 

    <ipython-input-13-20da15850b63> in <dictcomp>((k, g))
         10 
         11 
    ---> 12 scored_content_top_frames = {k: score(g) for k, g in content_top_frames.iteritems()}
         13 scored_parent_top_frames = {k: score(g) for k, g in parent_top_frames.iteritems()}
         14 

    <ipython-input-13-20da15850b63> in score(grouping)
          1 def score(grouping):
    ----> 2     grouping['hang_sum'] = float(grouping['hang_sum']) / float(total_sessions_length_m) * 1000
          3     scored_stacks = []
          4     for stack_tuple in grouping['stacks']:
          5         score = float(stack_tuple[1]) / float(total_sessions_length_m) * 1000

    NameError: global name 'total_sessions_length_m' is not defined

```python
import ujson as json

def write_file(name, stuff):
    filename = "%s-%s-%s.json" % (name, startDate, endDate)
    jsonblob = json.dumps(stuff, ensure_ascii=False, sort_keys=True, indent=4)

    with open("output/%s" % filename, 'w') as f:
        f.write(jsonblob)
    
    return filename

content_file_name = write_file('content', sorted_content)
parent_file_name = write_file('parent', sorted_parent)

```

    

    NameErrorTraceback (most recent call last)

    <ipython-input-14-6d032be68a7e> in <module>()
         10     return filename
         11 
    ---> 12 content_file_name = write_file('content', sorted_content)
         13 parent_file_name = write_file('parent', sorted_parent)

    NameError: name 'sorted_content' is not defined

```python
from zipfile import ZipFile, ZIP_DEFLATED

with ZipFile("./output/snapshot-%s-%s.zip" % (startDate, endDate), 'w', ZIP_DEFLATED) as myzip:
    myzip.write("output/%s" % content_file_name, content_file_name, ZIP_DEFLATED)
    myzip.write("output/%s" % parent_file_name, parent_file_name, ZIP_DEFLATED)
```

    

    NameErrorTraceback (most recent call last)

    <ipython-input-15-a32e7e32b432> in <module>()
          2 
          3 with ZipFile("./output/snapshot-%s-%s.zip" % (startDate, endDate), 'w', ZIP_DEFLATED) as myzip:
    ----> 4     myzip.write("output/%s" % content_file_name, content_file_name, ZIP_DEFLATED)
          5     myzip.write("output/%s" % parent_file_name, parent_file_name, ZIP_DEFLATED)

    NameError: name 'content_file_name' is not defined

```python
with ZipFile("./output/snapshot-daily.zip", 'w', ZIP_DEFLATED) as myzip:
    myzip.write("output/%s" % content_file_name, content_file_name, ZIP_DEFLATED)
    myzip.write("output/%s" % parent_file_name, parent_file_name, ZIP_DEFLATED)
```

    

    NameErrorTraceback (most recent call last)

    <ipython-input-16-9bd37fca5411> in <module>()
          1 with ZipFile("./output/snapshot-daily.zip", 'w', ZIP_DEFLATED) as myzip:
    ----> 2     myzip.write("output/%s" % content_file_name, content_file_name, ZIP_DEFLATED)
          3     myzip.write("output/%s" % parent_file_name, parent_file_name, ZIP_DEFLATED)

    NameError: name 'content_file_name' is not defined

**Comment by jezdez** [comment]
Closing since the job isn't tracked in ATMO anymore.
